services:
  web:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
      target: dev
    command: yarn nodemon index.ts
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resume